/** Display names for common Binance base assets (EUR pairs). */
export const COIN_DISPLAY_NAMES: Record<string, string> = {
  BTC: "Bitcoin",
  ETH: "Ethereum",
  SOL: "Solana",
  XRP: "XRP",
  ADA: "Cardano",
  DOGE: "Dogecoin",
  DOT: "Polkadot",
  AVAX: "Avalanche",
  LINK: "Chainlink",
  LTC: "Litecoin",
  BCH: "Bitcoin Cash",
  UNI: "Uniswap",
  ATOM: "Cosmos",
  XLM: "Stellar",
  NEAR: "NEAR Protocol",
  APT: "Aptos",
  ARB: "Arbitrum",
  OP: "Optimism",
  SUI: "Sui",
  TON: "Toncoin",
  TRX: "TRON",
  SHIB: "Shiba Inu",
  PEPE: "Pepe",
  FIL: "Filecoin",
  AAVE: "Aave",
  MKR: "Maker",
  CRV: "Curve",
  LDO: "Lido DAO",
  INJ: "Injective",
  RNDR: "Render",
  RENDER: "Render",
  FET: "Fetch.ai",
  TAO: "Bittensor",
  SEI: "Sei",
  TIA: "Celestia",
  HBAR: "Hedera",
  ALGO: "Algorand",
  VET: "VeChain",
  EGLD: "MultiversX",
  SAND: "The Sandbox",
  MANA: "Decentraland",
  AXS: "Axie Infinity",
  GALA: "Gala",
  IMX: "Immutable",
  GRT: "The Graph",
  ENS: "Ethereum Name Service",
  COMP: "Compound",
  SNX: "Synthetix",
  SUSHI: "SushiSwap",
  YFI: "yearn.finance",
  CAKE: "PancakeSwap",
  BNB: "BNB",
  ETC: "Ethereum Classic",
  XMR: "Monero",
  ZEC: "Zcash",
  DASH: "Dash",
  EOS: "EOS",
  XTZ: "Tezos",
  THETA: "Theta",
  FLOW: "Flow",
  ICP: "Internet Computer",
  APTOS: "Aptos",
  WLD: "Worldcoin",
  ONDO: "Ondo",
  ENA: "Ethena",
  JUP: "Jupiter",
  PYTH: "Pyth Network",
  BONK: "Bonk",
  WIF: "dogwifhat",
  FLOKI: "FLOKI",
  POL: "Polygon",
  MATIC: "Polygon",
};

export function coinDisplayName(baseAsset: string): string {
  const key = baseAsset.trim().toUpperCase();
  return COIN_DISPLAY_NAMES[key] ?? baseAsset;
}
